name: Terraform Deploy

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan.out
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.out
        working-directory: infra
